# Generated by Django 2.1.1 on 2019-11-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('photo6', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('photo7', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('photo8', models.ImageField(blank=True, null=True, upload_to='news/')),
            ],
        ),
    ]
